
language: cpp

git:
    depth: 5

addons: 
  apt:
    sources:
    - ubuntu-toolchain-r-test # cmake requirement

    packages:
    - [cmake, cmake-data]
    - ccache
    - ninja-build
    - [gcc-5, g++-5]

matrix:
  allow_failures:
    - os: linux
      compiler: clang

  include: 
    # Linux

    ## Clang
    - os: linux
      env: COMPILER=clang++ CMAKE_BUILD_TYPE=Release CMAKE_GENERATOR=Ninja
      compiler: clang

    - os: linux
      env: COMPILER=clang++ CMAKE_BUILD_TYPE=Debug CMAKE_GENERATOR=Ninja
      compiler: clang

    ## gcc
    - os: linux
      env: COMPILER=g++-5 CMAKE_BUILD_TYPE=Debug CMAKE_GENERATOR=Ninja
      compiler: gcc

    - os: linux
      env: COMPILER=g++-5 CMAKE_BUILD_TYPE=Release CMAKE_GENERATOR=Ninja
      compiler: gcc


    # Mac OSX
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug CMAKE_GENERATOR=Ninja 

    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release CMAKE_GENERATOR=Ninja

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: CMAKE_BUILD_TYPE=Release CMAKE_GENERATOR=Ninja 

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug CMAKE_GENERATOR=Xcode  

cache:
  directories:
    - $HOME/.ccache

before_install:
- |
    case `uname` in 
        Darwin)     export OS_NAME="osx"    ;;
        Linux)      export OS_NAME="linux"  ;;
    esac

    if [[ ${OS_NAME} == osx ]]; then
        brew update
        brew install ninja
    fi

- |
    if [[ ${OS_NAME} == linux ]]; then
        case ${COMPILER} in
            clang*)
                export CC=$(echo ${COMPILER} | sed 's/\+//g')
                export CXX=${COMPILER}
            ;;

            g++-*)
                export CC=$(echo ${COMPILER} | sed 's/\+/c/g')
                export CXX=${COMPILER} 
            ;;

            *) echo "Invalid compiler version" ; exit 2 ;;
        esac
    fi

script:

- |
  cmake --version
  ninja --version 

  echo "CC=${CC}"
  $CC --version
  echo "CXX=${CXX}"
  $CXX --version

- mkdir build; cd build
- |
    cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
          -G${CMAKE_GENERATOR} \
          ..

- cmake --build . --target check

notifications:
    email:
        on_success: change
        on_failure: change
